services:
  db:
    image: postgres:16
    healthcheck:
      test: ["CMD", "pg_isready", "--username=postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    depends_on:
      - db
    image: ${WEB_IMAGE:-ghcr.io/kaze/kanban:latest}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      DATABASE_URL: ecto://postgres:postgres@db/postgres
      SECRET_KEY_BASE: B2oPsqBBfZjl4BuHk8C69re829YkZ8R0kHOZVqUEczypGPEaN9WcoOyzfjLiIdom
      PHX_HOST: localhost
    ports:
      - 4000:4000
    command: >
      bash -c "bin/migrate && bin/server"

volumes:
  db_data:
